### ISSUE TITLE
What mean for "PB1 - ADXL345 IRQ line"?

### ISSUE THREAD

**Issue by lipk888** [iliasam/MBalancing#1]
Hi iliasam:
Firstly, thanks for design nice project.
i have confuse for STM32 PIN connect for "PB1 - ADXL345 IRQ line"
you know ASXL345 not have IRO interface, do you mean ADXL345's INT1 connect to PB1?

**Comment by iliasam** [comment]
Hello.
You are right, thank you. I had updated project description.

**Comment by lipk888** [comment]
> Hello. You are right, thank you. I had updated project description.

==========================================
Thanks, iliasam.
Also i have suggestion, add 2th ADXL345 on the STM32 board to support motor's rotor balance.
the detial idea below, Add new nCS pin for 2th ADXL345, then add two key to select 1th or 2th  ADXL345, Also need two LED to point out which ADXL345 selected. this idea will not affect PC software.

**Comment by iliasam** [comment]
Sorry, I don't have plans to improve this project now.
But it any case, I don't understand how you want to use second  ADXL345.

**Comment by lipk888** [comment]
got it, many thanks
